#datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.0.13.46:3306/paas?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
#    username: db_writer
#    password: ka_32^%*ko
    url: jdbc:mysql://localhost:3306/paas?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root564907422
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true

logging:
  file: /home/darren/logs/paas-service-web.log
  level:
    com:
      paas: debug
    org:
      springframework:
        web: debug
      hibernate: debug

server:
  port: 8085
